export EDITOR=nvim
export GIT_EDITOR=nvim

HIST_STAMPS="dd/mm/yyyy"

[ -f ~/.config/secrets/env ] && source ~/.config/secrets/env

# -------------------------------- #
# Oh My Zsh
# -------------------------------- #

# git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)
eval "$(zoxide init zsh)"

typeset -U path cdpath fpath
path=(
    $HOME/.local/bin
    $HOME/Code/AssetsAndTemplates/dotfiles/scripts
    $path
)

ZSH_THEME="my"
export ZSH=$HOME/.oh-my-zsh
zstyle ':omz:alpha:lib:git' async-prompt no
source $ZSH/oh-my-zsh.sh

## commands
ZSH_HIGHLIGHT_STYLES[command]='fg=107'

## unknown / invalid commands
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=167'

## builtins / aliases / functions
ZSH_HIGHLIGHT_STYLES[builtin]='fg=107'
ZSH_HIGHLIGHT_STYLES[alias]='fg=107'
ZSH_HIGHLIGHT_STYLES[function]='fg=107'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=107'

## paths
ZSH_HIGHLIGHT_STYLES[path]='fg=244,underline'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=244'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=244,underline'

## strings
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=179'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=179'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=179'

## options: -l, --help, etc.
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=109'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=109'

## variables
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=110'
ZSH_HIGHLIGHT_STYLES[assign]='fg=110'

## redirections/operators
ZSH_HIGHLIGHT_STYLES[redirection]='fg=109'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=244'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg=244'
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg=244'

## comments
ZSH_HIGHLIGHT_STYLES[comment]='fg=240'

# Paths
export PATH="$PATH:$HOME/.dotnet/tools"
export PATH="$HOME/.composer/vendor/bin:$PATH"

# Spelling correction
setopt correctall

# Selection in autocompletion
setopt menucomplete
zstyle ':completion:*' menu select=1 _complete _ignored _approximate

#--------------------------------------------------------------------------
# Useful functions
#--------------------------------------------------------------------------
function cpr() {
  cd ~/Yandex.Disk.localized/Work/ClientsProjects
}

function D() {
  cd ~/Downloads
}

function mkd() {
  mkdir -p $1 && cd $1
}

function cursor {
  open -a "/Applications/Cursor.app" "$@"
}

#--------------------------------------------------------------------------
# Aliases
#--------------------------------------------------------------------------

alias vi="nvim"
alias ot="open -a \"Telegram\""
alias sail='[ -f sail ] && sail || vendor/bin/sail'
alias ls="ls -laFhG"

# Git
# Go to project root
alias grt='cd "$(git rev-parse --show-toplevel)"'
alias gs='git status'
alias gA='git add -A'
alias gc='git commit'
